INSERT INTO `day_4 exercise` VALUES ('DOE,JOHN');
INSERT INTO `day_4 exercise` VALUES ('SMITH,JANE');
INSERT INTO `day_4 exercise` VALUES ('JOHNSON,BOB');
INSERT INTO `day_4 exercise` VALUES ('BROWN,ALICE');
INSERT INTO `day_4 exercise` VALUES ('WILSON,CHARLIE');
INSERT INTO `day_4 exercise` VALUES ('LEE,DIANA');
INSERT INTO `day_4 exercise` VALUES ('John', 4);
INSERT INTO `day_4 exercise` VALUES ('Jane', 4);
INSERT INTO `day_4 exercise` VALUES ('Bob', 3);
INSERT INTO `day_4 exercise` VALUES ('Alice', 5);
INSERT INTO `day_4 exercise` VALUES ('Charlie', 7);
INSERT INTO `day_4 exercise` VALUES ('Diana', 5);
INSERT INTO `day_4 exercise` VALUES ('Doe,John', 1980);
INSERT INTO `day_4 exercise` VALUES ('Smith,Jane', 1982);
INSERT INTO `day_4 exercise` VALUES ('Johnson,Bob', 1978);
INSERT INTO `day_4 exercise` VALUES ('Brown,Alice', 1990);
INSERT INTO `day_4 exercise` VALUES ('Wilson,Charlie', 1985);
INSERT INTO `day_4 exercise` VALUES ('Lee,Diana', 1988);
INSERT INTO `day_4 exercise` VALUES ('Doe,John', '2005-6-1', 20);
INSERT INTO `day_4 exercise` VALUES ('Smith,Jane', '2006-8-15', 19);
INSERT INTO `day_4 exercise` VALUES ('Johnson,Bob', '2004-3-20', 21);
INSERT INTO `day_4 exercise` VALUES ('Brown,Alice', '2010-11-11', 15);
INSERT INTO `day_4 exercise` VALUES ('Wilson,Charlie', '2007-5-30', 18);
INSERT INTO `day_4 exercise` VALUES ('Lee,Diana', '2009-9-9', 16);
INSERT INTO `day_4 exercise` VALUES ('Doe,John', '2005-6-1', 20);
INSERT INTO `day_4 exercise` VALUES ('Smith,Jane', '2006-8-15', 19);
INSERT INTO `day_4 exercise` VALUES ('Johnson,Bob', '2004-3-20', 21);
INSERT INTO `day_4 exercise` VALUES ('Brown,Alice', '2010-11-11', 15);
INSERT INTO `day_4 exercise` VALUES ('Wilson,Charlie', '2007-5-30', 18);
INSERT INTO `day_4 exercise` VALUES ('Lee,Diana', '2009-9-9', 16);
INSERT INTO `day_4 exercise` VALUES ('员工John Doe于2005年入职');
INSERT INTO `day_4 exercise` VALUES ('员工Jane Smith于2006年入职');
INSERT INTO `day_4 exercise` VALUES ('员工Bob Johnson于2004年入职');
INSERT INTO `day_4 exercise` VALUES ('员工Alice Brown于2010年入职');
INSERT INTO `day_4 exercise` VALUES ('员工Charlie Wilson于2007年入职');
INSERT INTO `day_4 exercise` VALUES ('员工Diana Lee于2009年入职');
